# Generated by Django 4.2.7 on 2023-11-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_role_profile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
