# Generated by Django 4.2.7 on 2023-11-18 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0007_alter_profile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
