# Generated by Django 4.2.7 on 2023-11-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_role_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='group',
        ),
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(to='users.role'),
        ),
    ]
